### ISSUE TITLE
Haven't seen FedCL in FLAlgorithm 

### ISSUE THREAD

**Issue by maskedw0lf** [MingjieWang0606/FedCL_Pubic#1]

**Comment by MingjieWang0606** [comment]
The latest version of has been updated. You can use FedCL :)
BTW, the previous readme wrote 'There is a main file "main.py" which allows running all experiments. The fedgen in this code is fedcl. If you want to run fedgen, please use the [code](https://github.com/zhuangdizhu/FedGen/blob/main/FLAlgorithms/servers/serverpFedGen.py).'
