### ISSUE TITLE
代码跑不通

### ISSUE THREAD

**Issue by s2drag0n** [MingjieWang0606/FedCL_Pubic#2]
请问这是正确的代码吗，我改了很多个地方可以跑通了，但是感觉自己跑的可能不对。

**Comment by MingjieWang0606** [comment]
同学你好，在文章录取之后，我会更新github。

**Comment by s2drag0n** [comment]
好的，谢谢

**Comment by MingjieWang0606** [comment]
我测试了目前的代码，是可以跑通的。
你可以检查你的环境，我使用的环境与fedgen的环境是一致的。
